version: '3.9'
services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    depends_on:
      - database
    restart: always
    volumes:
      - /var/www/code:/app
      - /var/www/config:/etc/nginx/conf.d
  php:
    image: php:8-fpm-alpine
    volumes:
      - /var/www/code:/app
    restart: always
    depends_on:
      - database
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=database
      - UPLOAD_LIMIT=300000
    ports:
      - '30002:80'
